"""empty message

Revision ID: 3b68f86191f6
Revises: 83910a39aada
Create Date: 2024-12-16 11:57:55.762314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b68f86191f6'
down_revision = '83910a39aada'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('orientation', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('sober_status', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_table', schema=None) as batch_op:
        batch_op.drop_column('sober_status')
        batch_op.drop_column('orientation')
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
