"""added user blocking functionallity

Revision ID: 50abf457b65e
Revises: a8d5a58f2a35
Create Date: 2025-06-09 15:32:24.144985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50abf457b65e'
down_revision = 'a8d5a58f2a35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blocker_id', sa.Integer(), nullable=False),
    sa.Column('blocked_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.CheckConstraint('blocker_id != blocked_id', name='no_self_block'),
    sa.ForeignKeyConstraint(['blocked_id'], ['users_table.id'], ),
    sa.ForeignKeyConstraint(['blocker_id'], ['users_table.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blocker_id', 'blocked_id', name='unique_block_pair')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_blocks')
    # ### end Alembic commands ###
