"""empty message

Revision ID: d498e2cc93da
Revises: 7a5dd0f899f5
Create Date: 2025-04-08 13:04:10.165313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd498e2cc93da'
down_revision = '7a5dd0f899f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events_table', schema=None) as batch_op:
        batch_op.drop_column('photo')

    # ### end Alembic commands ###
